// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
// v1.0.0
// protocol
type Proto struct {
	Ver                  int32    `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Op                   int32    `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Seq                  int32    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Body                 []byte   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	SessionKey           string   `protobuf:"bytes,5,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	UserId               int64    `protobuf:"varint,6,opt,name=userId,proto3" json:"userId,omitempty"`
	LineId               string   `protobuf:"bytes,7,opt,name=lineId,proto3" json:"lineId,omitempty"`
	AgencyId             string   `protobuf:"bytes,8,opt,name=agencyId,proto3" json:"agencyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proto) Reset()         { *m = Proto{} }
func (m *Proto) String() string { return proto.CompactTextString(m) }
func (*Proto) ProtoMessage()    {}
func (*Proto) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Proto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proto.Unmarshal(m, b)
}
func (m *Proto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proto.Marshal(b, m, deterministic)
}
func (m *Proto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proto.Merge(m, src)
}
func (m *Proto) XXX_Size() int {
	return xxx_messageInfo_Proto.Size(m)
}
func (m *Proto) XXX_DiscardUnknown() {
	xxx_messageInfo_Proto.DiscardUnknown(m)
}

var xxx_messageInfo_Proto proto.InternalMessageInfo

func (m *Proto) GetVer() int32 {
	if m != nil {
		return m.Ver
	}
	return 0
}

func (m *Proto) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *Proto) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Proto) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Proto) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

func (m *Proto) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Proto) GetLineId() string {
	if m != nil {
		return m.LineId
	}
	return ""
}

func (m *Proto) GetAgencyId() string {
	if m != nil {
		return m.AgencyId
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PushMsgReq struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	ProtoOp              int32    `protobuf:"varint,3,opt,name=protoOp,proto3" json:"protoOp,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	LineId               string   `protobuf:"bytes,4,opt,name=lineId,proto3" json:"lineId,omitempty"`
	AgencyId             string   `protobuf:"bytes,5,opt,name=agencyId,proto3" json:"agencyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (m *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(m, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *PushMsgReq) GetProtoOp() int32 {
	if m != nil {
		return m.ProtoOp
	}
	return 0
}

func (m *PushMsgReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

func (m *PushMsgReq) GetLineId() string {
	if m != nil {
		return m.LineId
	}
	return ""
}

func (m *PushMsgReq) GetAgencyId() string {
	if m != nil {
		return m.AgencyId
	}
	return ""
}

type PushMsgReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgReply) Reset()         { *m = PushMsgReply{} }
func (m *PushMsgReply) String() string { return proto.CompactTextString(m) }
func (*PushMsgReply) ProtoMessage()    {}
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PushMsgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReply.Unmarshal(m, b)
}
func (m *PushMsgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReply.Marshal(b, m, deterministic)
}
func (m *PushMsgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReply.Merge(m, src)
}
func (m *PushMsgReply) XXX_Size() int {
	return xxx_messageInfo_PushMsgReply.Size(m)
}
func (m *PushMsgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReply.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReply proto.InternalMessageInfo

type BroadcastReq struct {
	ProtoOp              int32    `protobuf:"varint,1,opt,name=protoOp,proto3" json:"protoOp,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Speed                int32    `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReq) Reset()         { *m = BroadcastReq{} }
func (m *BroadcastReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastReq) ProtoMessage()    {}
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *BroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReq.Unmarshal(m, b)
}
func (m *BroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReq.Marshal(b, m, deterministic)
}
func (m *BroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReq.Merge(m, src)
}
func (m *BroadcastReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastReq.Size(m)
}
func (m *BroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReq proto.InternalMessageInfo

func (m *BroadcastReq) GetProtoOp() int32 {
	if m != nil {
		return m.ProtoOp
	}
	return 0
}

func (m *BroadcastReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

func (m *BroadcastReq) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type BroadcastReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReply) Reset()         { *m = BroadcastReply{} }
func (m *BroadcastReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastReply) ProtoMessage()    {}
func (*BroadcastReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *BroadcastReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReply.Unmarshal(m, b)
}
func (m *BroadcastReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReply.Marshal(b, m, deterministic)
}
func (m *BroadcastReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReply.Merge(m, src)
}
func (m *BroadcastReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastReply.Size(m)
}
func (m *BroadcastReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReply proto.InternalMessageInfo

type BroadcastRoomReq struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRoomReq) Reset()         { *m = BroadcastRoomReq{} }
func (m *BroadcastRoomReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastRoomReq) ProtoMessage()    {}
func (*BroadcastRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *BroadcastRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRoomReq.Unmarshal(m, b)
}
func (m *BroadcastRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRoomReq.Marshal(b, m, deterministic)
}
func (m *BroadcastRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRoomReq.Merge(m, src)
}
func (m *BroadcastRoomReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastRoomReq.Size(m)
}
func (m *BroadcastRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRoomReq proto.InternalMessageInfo

func (m *BroadcastRoomReq) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *BroadcastRoomReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type BroadcastRoomReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRoomReply) Reset()         { *m = BroadcastRoomReply{} }
func (m *BroadcastRoomReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastRoomReply) ProtoMessage()    {}
func (*BroadcastRoomReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *BroadcastRoomReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRoomReply.Unmarshal(m, b)
}
func (m *BroadcastRoomReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRoomReply.Marshal(b, m, deterministic)
}
func (m *BroadcastRoomReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRoomReply.Merge(m, src)
}
func (m *BroadcastRoomReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastRoomReply.Size(m)
}
func (m *BroadcastRoomReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRoomReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRoomReply proto.InternalMessageInfo

type RoomsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomsReq) Reset()         { *m = RoomsReq{} }
func (m *RoomsReq) String() string { return proto.CompactTextString(m) }
func (*RoomsReq) ProtoMessage()    {}
func (*RoomsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *RoomsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomsReq.Unmarshal(m, b)
}
func (m *RoomsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomsReq.Marshal(b, m, deterministic)
}
func (m *RoomsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomsReq.Merge(m, src)
}
func (m *RoomsReq) XXX_Size() int {
	return xxx_messageInfo_RoomsReq.Size(m)
}
func (m *RoomsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomsReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomsReq proto.InternalMessageInfo

type RoomsReply struct {
	Rooms                map[string]bool `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RoomsReply) Reset()         { *m = RoomsReply{} }
func (m *RoomsReply) String() string { return proto.CompactTextString(m) }
func (*RoomsReply) ProtoMessage()    {}
func (*RoomsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *RoomsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomsReply.Unmarshal(m, b)
}
func (m *RoomsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomsReply.Marshal(b, m, deterministic)
}
func (m *RoomsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomsReply.Merge(m, src)
}
func (m *RoomsReply) XXX_Size() int {
	return xxx_messageInfo_RoomsReply.Size(m)
}
func (m *RoomsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomsReply.DiscardUnknown(m)
}

var xxx_messageInfo_RoomsReply proto.InternalMessageInfo

func (m *RoomsReply) GetRooms() map[string]bool {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type JoinRoomReq struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomReq) Reset()         { *m = JoinRoomReq{} }
func (m *JoinRoomReq) String() string { return proto.CompactTextString(m) }
func (*JoinRoomReq) ProtoMessage()    {}
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *JoinRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomReq.Unmarshal(m, b)
}
func (m *JoinRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomReq.Marshal(b, m, deterministic)
}
func (m *JoinRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomReq.Merge(m, src)
}
func (m *JoinRoomReq) XXX_Size() int {
	return xxx_messageInfo_JoinRoomReq.Size(m)
}
func (m *JoinRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomReq proto.InternalMessageInfo

func (m *JoinRoomReq) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *JoinRoomReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type JoinRoomeResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Tokken               string   `protobuf:"bytes,2,opt,name=tokken,proto3" json:"tokken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomeResp) Reset()         { *m = JoinRoomeResp{} }
func (m *JoinRoomeResp) String() string { return proto.CompactTextString(m) }
func (*JoinRoomeResp) ProtoMessage()    {}
func (*JoinRoomeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *JoinRoomeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomeResp.Unmarshal(m, b)
}
func (m *JoinRoomeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomeResp.Marshal(b, m, deterministic)
}
func (m *JoinRoomeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomeResp.Merge(m, src)
}
func (m *JoinRoomeResp) XXX_Size() int {
	return xxx_messageInfo_JoinRoomeResp.Size(m)
}
func (m *JoinRoomeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomeResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomeResp proto.InternalMessageInfo

func (m *JoinRoomeResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *JoinRoomeResp) GetTokken() string {
	if m != nil {
		return m.Tokken
	}
	return ""
}

type LeaveRoomReq struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomReq) Reset()         { *m = LeaveRoomReq{} }
func (m *LeaveRoomReq) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomReq) ProtoMessage()    {}
func (*LeaveRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *LeaveRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomReq.Unmarshal(m, b)
}
func (m *LeaveRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomReq.Marshal(b, m, deterministic)
}
func (m *LeaveRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomReq.Merge(m, src)
}
func (m *LeaveRoomReq) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomReq.Size(m)
}
func (m *LeaveRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomReq proto.InternalMessageInfo

func (m *LeaveRoomReq) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *LeaveRoomReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type LeaveRoomResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomResp) Reset()         { *m = LeaveRoomResp{} }
func (m *LeaveRoomResp) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomResp) ProtoMessage()    {}
func (*LeaveRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *LeaveRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomResp.Unmarshal(m, b)
}
func (m *LeaveRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomResp.Marshal(b, m, deterministic)
}
func (m *LeaveRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomResp.Merge(m, src)
}
func (m *LeaveRoomResp) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomResp.Size(m)
}
func (m *LeaveRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomResp proto.InternalMessageInfo

func (m *LeaveRoomResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type CancelRoomReq struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRoomReq) Reset()         { *m = CancelRoomReq{} }
func (m *CancelRoomReq) String() string { return proto.CompactTextString(m) }
func (*CancelRoomReq) ProtoMessage()    {}
func (*CancelRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *CancelRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRoomReq.Unmarshal(m, b)
}
func (m *CancelRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRoomReq.Marshal(b, m, deterministic)
}
func (m *CancelRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRoomReq.Merge(m, src)
}
func (m *CancelRoomReq) XXX_Size() int {
	return xxx_messageInfo_CancelRoomReq.Size(m)
}
func (m *CancelRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRoomReq proto.InternalMessageInfo

func (m *CancelRoomReq) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *CancelRoomReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type CancelRoomResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRoomResp) Reset()         { *m = CancelRoomResp{} }
func (m *CancelRoomResp) String() string { return proto.CompactTextString(m) }
func (*CancelRoomResp) ProtoMessage()    {}
func (*CancelRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *CancelRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRoomResp.Unmarshal(m, b)
}
func (m *CancelRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRoomResp.Marshal(b, m, deterministic)
}
func (m *CancelRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRoomResp.Merge(m, src)
}
func (m *CancelRoomResp) XXX_Size() int {
	return xxx_messageInfo_CancelRoomResp.Size(m)
}
func (m *CancelRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRoomResp proto.InternalMessageInfo

func (m *CancelRoomResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type RoomInfoReq struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfoReq) Reset()         { *m = RoomInfoReq{} }
func (m *RoomInfoReq) String() string { return proto.CompactTextString(m) }
func (*RoomInfoReq) ProtoMessage()    {}
func (*RoomInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *RoomInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfoReq.Unmarshal(m, b)
}
func (m *RoomInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfoReq.Marshal(b, m, deterministic)
}
func (m *RoomInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfoReq.Merge(m, src)
}
func (m *RoomInfoReq) XXX_Size() int {
	return xxx_messageInfo_RoomInfoReq.Size(m)
}
func (m *RoomInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfoReq proto.InternalMessageInfo

func (m *RoomInfoReq) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *RoomInfoReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type RoomInfoResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Mid                  []int64  `protobuf:"varint,3,rep,packed,name=mid,proto3" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfoResp) Reset()         { *m = RoomInfoResp{} }
func (m *RoomInfoResp) String() string { return proto.CompactTextString(m) }
func (*RoomInfoResp) ProtoMessage()    {}
func (*RoomInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *RoomInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfoResp.Unmarshal(m, b)
}
func (m *RoomInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfoResp.Marshal(b, m, deterministic)
}
func (m *RoomInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfoResp.Merge(m, src)
}
func (m *RoomInfoResp) XXX_Size() int {
	return xxx_messageInfo_RoomInfoResp.Size(m)
}
func (m *RoomInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfoResp proto.InternalMessageInfo

func (m *RoomInfoResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *RoomInfoResp) GetMid() []int64 {
	if m != nil {
		return m.Mid
	}
	return nil
}

type RoomInfo struct {
	RoomID               string   `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	RoomCount            int64    `protobuf:"varint,2,opt,name=RoomCount,proto3" json:"RoomCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *RoomInfo) GetRoomCount() int64 {
	if m != nil {
		return m.RoomCount
	}
	return 0
}

type JoinRoomsReq struct {
	RoomID               []int64  `protobuf:"varint,1,rep,packed,name=roomID,proto3" json:"roomID,omitempty"`
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomsReq) Reset()         { *m = JoinRoomsReq{} }
func (m *JoinRoomsReq) String() string { return proto.CompactTextString(m) }
func (*JoinRoomsReq) ProtoMessage()    {}
func (*JoinRoomsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *JoinRoomsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomsReq.Unmarshal(m, b)
}
func (m *JoinRoomsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomsReq.Marshal(b, m, deterministic)
}
func (m *JoinRoomsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomsReq.Merge(m, src)
}
func (m *JoinRoomsReq) XXX_Size() int {
	return xxx_messageInfo_JoinRoomsReq.Size(m)
}
func (m *JoinRoomsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomsReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomsReq proto.InternalMessageInfo

func (m *JoinRoomsReq) GetRoomID() []int64 {
	if m != nil {
		return m.RoomID
	}
	return nil
}

func (m *JoinRoomsReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type JoinRoomesResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Tokken               string   `protobuf:"bytes,2,opt,name=tokken,proto3" json:"tokken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomesResp) Reset()         { *m = JoinRoomesResp{} }
func (m *JoinRoomesResp) String() string { return proto.CompactTextString(m) }
func (*JoinRoomesResp) ProtoMessage()    {}
func (*JoinRoomesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *JoinRoomesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomesResp.Unmarshal(m, b)
}
func (m *JoinRoomesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomesResp.Marshal(b, m, deterministic)
}
func (m *JoinRoomesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomesResp.Merge(m, src)
}
func (m *JoinRoomesResp) XXX_Size() int {
	return xxx_messageInfo_JoinRoomesResp.Size(m)
}
func (m *JoinRoomesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomesResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomesResp proto.InternalMessageInfo

func (m *JoinRoomesResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *JoinRoomesResp) GetTokken() string {
	if m != nil {
		return m.Tokken
	}
	return ""
}

type RoomUserCountReq struct {
	Proto                *Proto   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomUserCountReq) Reset()         { *m = RoomUserCountReq{} }
func (m *RoomUserCountReq) String() string { return proto.CompactTextString(m) }
func (*RoomUserCountReq) ProtoMessage()    {}
func (*RoomUserCountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *RoomUserCountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomUserCountReq.Unmarshal(m, b)
}
func (m *RoomUserCountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomUserCountReq.Marshal(b, m, deterministic)
}
func (m *RoomUserCountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomUserCountReq.Merge(m, src)
}
func (m *RoomUserCountReq) XXX_Size() int {
	return xxx_messageInfo_RoomUserCountReq.Size(m)
}
func (m *RoomUserCountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomUserCountReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoomUserCountReq proto.InternalMessageInfo

func (m *RoomUserCountReq) GetProto() *Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type RoomUserCountResp struct {
	RoomUserCount        []*RoomUserCount `protobuf:"bytes,1,rep,name=roomUserCount,proto3" json:"roomUserCount,omitempty"`
	Result               bool             `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RoomUserCountResp) Reset()         { *m = RoomUserCountResp{} }
func (m *RoomUserCountResp) String() string { return proto.CompactTextString(m) }
func (*RoomUserCountResp) ProtoMessage()    {}
func (*RoomUserCountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *RoomUserCountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomUserCountResp.Unmarshal(m, b)
}
func (m *RoomUserCountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomUserCountResp.Marshal(b, m, deterministic)
}
func (m *RoomUserCountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomUserCountResp.Merge(m, src)
}
func (m *RoomUserCountResp) XXX_Size() int {
	return xxx_messageInfo_RoomUserCountResp.Size(m)
}
func (m *RoomUserCountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomUserCountResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomUserCountResp proto.InternalMessageInfo

func (m *RoomUserCountResp) GetRoomUserCount() []*RoomUserCount {
	if m != nil {
		return m.RoomUserCount
	}
	return nil
}

func (m *RoomUserCountResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type RoomUserCount struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomUserCount) Reset()         { *m = RoomUserCount{} }
func (m *RoomUserCount) String() string { return proto.CompactTextString(m) }
func (*RoomUserCount) ProtoMessage()    {}
func (*RoomUserCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *RoomUserCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomUserCount.Unmarshal(m, b)
}
func (m *RoomUserCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomUserCount.Marshal(b, m, deterministic)
}
func (m *RoomUserCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomUserCount.Merge(m, src)
}
func (m *RoomUserCount) XXX_Size() int {
	return xxx_messageInfo_RoomUserCount.Size(m)
}
func (m *RoomUserCount) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomUserCount.DiscardUnknown(m)
}

var xxx_messageInfo_RoomUserCount proto.InternalMessageInfo

func (m *RoomUserCount) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomUserCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Proto)(nil), "goim.comet.Proto")
	proto.RegisterType((*Empty)(nil), "goim.comet.Empty")
	proto.RegisterType((*PushMsgReq)(nil), "goim.comet.PushMsgReq")
	proto.RegisterType((*PushMsgReply)(nil), "goim.comet.PushMsgReply")
	proto.RegisterType((*BroadcastReq)(nil), "goim.comet.BroadcastReq")
	proto.RegisterType((*BroadcastReply)(nil), "goim.comet.BroadcastReply")
	proto.RegisterType((*BroadcastRoomReq)(nil), "goim.comet.BroadcastRoomReq")
	proto.RegisterType((*BroadcastRoomReply)(nil), "goim.comet.BroadcastRoomReply")
	proto.RegisterType((*RoomsReq)(nil), "goim.comet.RoomsReq")
	proto.RegisterType((*RoomsReply)(nil), "goim.comet.RoomsReply")
	proto.RegisterMapType((map[string]bool)(nil), "goim.comet.RoomsReply.RoomsEntry")
	proto.RegisterType((*JoinRoomReq)(nil), "goim.comet.JoinRoomReq")
	proto.RegisterType((*JoinRoomeResp)(nil), "goim.comet.JoinRoomeResp")
	proto.RegisterType((*LeaveRoomReq)(nil), "goim.comet.LeaveRoomReq")
	proto.RegisterType((*LeaveRoomResp)(nil), "goim.comet.LeaveRoomResp")
	proto.RegisterType((*CancelRoomReq)(nil), "goim.comet.CancelRoomReq")
	proto.RegisterType((*CancelRoomResp)(nil), "goim.comet.CancelRoomResp")
	proto.RegisterType((*RoomInfoReq)(nil), "goim.comet.RoomInfoReq")
	proto.RegisterType((*RoomInfoResp)(nil), "goim.comet.RoomInfoResp")
	proto.RegisterType((*RoomInfo)(nil), "goim.comet.RoomInfo")
	proto.RegisterType((*JoinRoomsReq)(nil), "goim.comet.JoinRoomsReq")
	proto.RegisterType((*JoinRoomesResp)(nil), "goim.comet.JoinRoomesResp")
	proto.RegisterType((*RoomUserCountReq)(nil), "goim.comet.RoomUserCountReq")
	proto.RegisterType((*RoomUserCountResp)(nil), "goim.comet.RoomUserCountResp")
	proto.RegisterType((*RoomUserCount)(nil), "goim.comet.RoomUserCount")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 920 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x8f, 0xda, 0x46,
	0x10, 0xaf, 0x31, 0x06, 0x3c, 0x07, 0x88, 0xac, 0xae, 0xd4, 0x67, 0x5d, 0x0b, 0xf5, 0x4b, 0x78,
	0x68, 0x88, 0x74, 0x55, 0xd5, 0x53, 0xa2, 0x36, 0x17, 0x68, 0x54, 0xd1, 0xe6, 0xcf, 0x69, 0xd3,
	0xf4, 0xa1, 0x6f, 0xfc, 0xd9, 0x38, 0x16, 0xc6, 0x6b, 0xbc, 0xe6, 0x24, 0x7f, 0x80, 0x7e, 0x84,
	0xaa, 0x7d, 0xec, 0x07, 0xab, 0xf8, 0x00, 0x7c, 0x8a, 0x6a, 0xd6, 0x3e, 0xb3, 0xe6, 0xb8, 0xd3,
	0x35, 0xe5, 0xc5, 0xec, 0xcc, 0xce, 0xce, 0xfc, 0x66, 0x76, 0xe6, 0xb7, 0x80, 0x39, 0x0e, 0xbd,
	0x7e, 0x18, 0xf1, 0x98, 0x13, 0x70, 0xb9, 0xb7, 0xe8, 0x4f, 0xf9, 0x82, 0xc5, 0xf6, 0x23, 0xd7,
	0x8b, 0x3f, 0xac, 0x26, 0x28, 0x3d, 0x76, 0xb9, 0xcb, 0x1f, 0x4b, 0x93, 0xc9, 0xea, 0xbd, 0x94,
	0xa4, 0x20, 0x57, 0xe9, 0x51, 0xe7, 0x8f, 0x12, 0x18, 0x97, 0xd2, 0xc9, 0x09, 0xe8, 0x57, 0x2c,
	0xb2, 0xb4, 0xae, 0xd6, 0x33, 0x06, 0xd5, 0xcd, 0xba, 0x83, 0x22, 0xc5, 0x0f, 0x69, 0x43, 0x89,
	0x87, 0x56, 0x49, 0xee, 0x54, 0x36, 0xeb, 0x4e, 0x89, 0x87, 0xb4, 0xc4, 0x43, 0x3c, 0x22, 0xd8,
	0xd2, 0xd2, 0xb7, 0x47, 0x04, 0x5b, 0x52, 0xfc, 0x90, 0x53, 0x28, 0x4f, 0xf8, 0x2c, 0xb1, 0xca,
	0x5d, 0xad, 0x57, 0x1f, 0xd4, 0x36, 0xeb, 0x8e, 0x94, 0xa9, 0xfc, 0x92, 0x3e, 0x80, 0x60, 0x42,
	0x78, 0x3c, 0xf8, 0x99, 0x25, 0x96, 0xd1, 0xd5, 0x7a, 0xe6, 0xa0, 0xb9, 0x59, 0x77, 0x14, 0x2d,
	0x55, 0xd6, 0xc4, 0x81, 0xca, 0x4a, 0xb0, 0x68, 0x34, 0xb3, 0x2a, 0x5d, 0xad, 0xa7, 0x0f, 0x60,
	0xb3, 0xee, 0x64, 0x1a, 0x9a, 0xfd, 0xa2, 0x8d, 0xef, 0x05, 0x6c, 0x34, 0xb3, 0xaa, 0xd2, 0x9f,
	0xb4, 0x49, 0x35, 0x34, 0xfb, 0x25, 0x3d, 0xa8, 0x8d, 0x5d, 0x16, 0x4c, 0x93, 0xd1, 0xcc, 0xaa,
	0x49, 0xab, 0xfa, 0x66, 0xdd, 0xc9, 0x75, 0x34, 0x5f, 0x39, 0x55, 0x30, 0x5e, 0x2c, 0xc2, 0x38,
	0x71, 0xfe, 0xd4, 0x00, 0x2e, 0x57, 0xe2, 0xc3, 0x2b, 0xe1, 0x52, 0xb6, 0x24, 0x04, 0xca, 0x73,
	0x96, 0x08, 0x4b, 0xeb, 0xea, 0x3d, 0x93, 0xca, 0x35, 0xb1, 0xa0, 0x2a, 0x8b, 0xf9, 0x26, 0x4c,
	0x4b, 0x41, 0xaf, 0x45, 0xf2, 0x10, 0x0c, 0xb9, 0x94, 0xb5, 0x3b, 0x3a, 0x7b, 0xd0, 0xdf, 0x5e,
	0x54, 0x5f, 0x56, 0x9d, 0xa6, 0xfb, 0xa4, 0x9d, 0x83, 0xc7, 0x82, 0x99, 0x39, 0x60, 0x5b, 0x01,
	0x2c, 0xcb, 0xa4, 0x40, 0x6c, 0x42, 0x3d, 0x07, 0x16, 0xfa, 0x89, 0xe3, 0x42, 0x7d, 0x10, 0xf1,
	0xf1, 0x6c, 0x3a, 0x16, 0x31, 0x42, 0x55, 0x60, 0x69, 0x1f, 0x09, 0xeb, 0x18, 0x0c, 0x11, 0x32,
	0x36, 0xcb, 0xf2, 0x4a, 0x05, 0xa7, 0x05, 0x4d, 0x25, 0x10, 0x86, 0x7e, 0x0b, 0xad, 0xad, 0x86,
	0xf3, 0x05, 0x86, 0x6f, 0x43, 0x25, 0xe2, 0x7c, 0x31, 0xfa, 0x41, 0x46, 0x37, 0x69, 0x26, 0xdd,
	0x3b, 0xb8, 0x73, 0x0c, 0x64, 0xc7, 0x29, 0x86, 0x02, 0xa8, 0xa1, 0x20, 0x28, 0x5b, 0x3a, 0xbf,
	0x6b, 0x00, 0x99, 0x10, 0xfa, 0x09, 0xf9, 0x16, 0x0c, 0x8c, 0x91, 0x5e, 0xce, 0xd1, 0xd9, 0x97,
	0xaa, 0xe7, 0xad, 0x59, 0xba, 0x7c, 0x11, 0xc4, 0x51, 0x42, 0x53, 0x7b, 0xfb, 0x3c, 0x73, 0x23,
	0x95, 0xa4, 0x05, 0xfa, 0x9c, 0x25, 0x19, 0x6a, 0x5c, 0x62, 0x19, 0xae, 0xc6, 0xfe, 0x8a, 0x49,
	0xc8, 0x35, 0x9a, 0x0a, 0x4f, 0x4a, 0xe7, 0xda, 0x93, 0xf2, 0x5f, 0x7f, 0x77, 0x3e, 0x71, 0x5e,
	0xc3, 0xd1, 0x4f, 0xdc, 0x0b, 0x0e, 0x96, 0xf9, 0x33, 0x68, 0x5c, 0xfb, 0x63, 0x94, 0x89, 0x50,
	0x7a, 0x64, 0x62, 0xe5, 0xc7, 0xd2, 0x63, 0x8d, 0x66, 0x12, 0xea, 0x63, 0x3e, 0x9f, 0xb3, 0x40,
	0xba, 0x34, 0x69, 0x26, 0x39, 0x6f, 0xa0, 0xfe, 0x92, 0x8d, 0xaf, 0xd8, 0xc1, 0x10, 0x3d, 0x84,
	0x86, 0xe2, 0xf0, 0x76, 0x44, 0xce, 0x25, 0x34, 0x86, 0xe3, 0x60, 0xca, 0xfc, 0x83, 0x85, 0xee,
	0x41, 0x53, 0xf5, 0x78, 0x47, 0xec, 0xd7, 0x70, 0x84, 0x36, 0xa3, 0xe0, 0x3d, 0x3f, 0x48, 0xe4,
	0x73, 0xa8, 0x6f, 0xfd, 0xdd, 0x71, 0x0b, 0x2d, 0xd0, 0x17, 0x1e, 0xce, 0x88, 0xde, 0xd3, 0x29,
	0x2e, 0x9d, 0x8b, 0xb4, 0x49, 0xf1, 0xe4, 0xad, 0x30, 0x4e, 0xc1, 0x44, 0x9b, 0x21, 0x5f, 0x05,
	0xb1, 0x84, 0xa2, 0xd3, 0xad, 0x02, 0x6f, 0xf0, 0xba, 0x05, 0xc4, 0x6e, 0x32, 0x18, 0xe6, 0x3f,
	0x27, 0x73, 0x01, 0xcd, 0xbc, 0xa7, 0xc4, 0x47, 0x35, 0xd5, 0x53, 0x68, 0xe1, 0xe9, 0x77, 0x82,
	0x45, 0x12, 0x23, 0xc2, 0xba, 0x77, 0x78, 0x1f, 0x1e, 0xec, 0x1c, 0x16, 0x21, 0x79, 0x06, 0x8d,
	0x48, 0x55, 0x66, 0x83, 0x7b, 0xb2, 0x3b, 0xb8, 0xdb, 0x53, 0x45, 0x7b, 0x25, 0x85, 0x52, 0xa1,
	0x13, 0xbe, 0x83, 0x06, 0xbd, 0x61, 0x88, 0x05, 0x9b, 0x15, 0x2e, 0x61, 0x86, 0x93, 0x3d, 0x55,
	0x2e, 0x20, 0x15, 0xce, 0xfe, 0xa9, 0x80, 0x31, 0xc4, 0xe8, 0xe4, 0x2b, 0x28, 0x5f, 0x7a, 0x81,
	0x4b, 0x0a, 0x89, 0xc9, 0x87, 0xc1, 0xbe, 0xa9, 0x22, 0x8f, 0xc0, 0x18, 0xfa, 0x5c, 0xb0, 0x7b,
	0x9a, 0x3f, 0x85, 0x6a, 0x46, 0xe0, 0xa4, 0x5d, 0x28, 0x5c, 0xfe, 0xdc, 0xd8, 0xd6, 0x5e, 0x3d,
	0x92, 0xdd, 0x73, 0x30, 0x73, 0x76, 0x24, 0x05, 0x33, 0xf5, 0x11, 0xb0, 0xed, 0x5b, 0x76, 0xd0,
	0xc5, 0x2b, 0x68, 0x14, 0x08, 0x96, 0x9c, 0xee, 0x37, 0x4e, 0x27, 0xd9, 0xfe, 0xe2, 0x8e, 0x5d,
	0x74, 0xf7, 0x0d, 0x18, 0xb2, 0x5d, 0xc9, 0xf1, 0x1e, 0xe2, 0x5d, 0xda, 0xed, 0xfd, 0x74, 0x4c,
	0xbe, 0x87, 0xda, 0x75, 0x63, 0x92, 0xcf, 0x54, 0x1b, 0x85, 0x52, 0xed, 0x93, 0x7d, 0x1b, 0x29,
	0x37, 0x5e, 0x80, 0x99, 0x53, 0x53, 0xb1, 0x10, 0x2a, 0x05, 0x16, 0x3d, 0x14, 0xb9, 0x6c, 0x08,
	0xb0, 0x65, 0x18, 0x52, 0x30, 0x2c, 0x70, 0x59, 0xb1, 0x98, 0x3b, 0xa4, 0x34, 0x48, 0x5b, 0x0e,
	0x47, 0xde, 0xbf, 0x99, 0x8b, 0xc2, 0x4b, 0xc5, 0x3b, 0x2d, 0x10, 0xcc, 0x73, 0x30, 0xf3, 0xa1,
	0x2f, 0xa6, 0xa2, 0x72, 0x41, 0x11, 0xc6, 0xce, 0x50, 0xbf, 0xdc, 0xed, 0xfc, 0xd3, 0xdb, 0x87,
	0x89, 0x2d, 0xed, 0xcf, 0xef, 0xd8, 0x15, 0x21, 0xf9, 0x05, 0x3e, 0xfd, 0x95, 0xb1, 0x1f, 0xd9,
	0x24, 0x5a, 0x79, 0x73, 0x16, 0xbd, 0xc5, 0x7f, 0x64, 0xec, 0x9d, 0xf7, 0xff, 0xbc, 0x0e, 0x2a,
	0xbf, 0x95, 0xdd, 0x28, 0x9c, 0x4e, 0x2a, 0x92, 0x1a, 0xbe, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x07, 0xbe, 0x0b, 0x42, 0xca, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CometClient is the client API for Comet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CometClient interface {
	// Ping Service
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// Close Service
	Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	//PushMsg push by key or mid
	PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgReply, error)
	// Broadcast send to every enrity
	Broadcast(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*BroadcastReply, error)
	// BroadcastRoom broadcast to one room
	BroadcastRoom(ctx context.Context, in *BroadcastRoomReq, opts ...grpc.CallOption) (*BroadcastRoomReply, error)
	// Rooms get all rooms
	Rooms(ctx context.Context, in *RoomsReq, opts ...grpc.CallOption) (*RoomsReply, error)
	// 进入房间
	JoinRoom(ctx context.Context, in *JoinRoomReq, opts ...grpc.CallOption) (*JoinRoomeResp, error)
	// 退出房间
	LeaveRoom(ctx context.Context, in *LeaveRoomReq, opts ...grpc.CallOption) (*LeaveRoomResp, error)
	// 注销房间
	CancelRoom(ctx context.Context, in *CancelRoomReq, opts ...grpc.CallOption) (*CancelRoomResp, error)
	// 房间信息
	RoomInfolRoom(ctx context.Context, in *RoomInfoReq, opts ...grpc.CallOption) (*RoomInfoResp, error)
	// 进入多房间
	JoinRooms(ctx context.Context, in *JoinRoomsReq, opts ...grpc.CallOption) (*JoinRoomesResp, error)
	// 房间人数
	RoomUserCount(ctx context.Context, in *RoomUserCountReq, opts ...grpc.CallOption) (*RoomUserCountResp, error)
	// 接收人是否在线
	VeeGebruikerSessieUit(ctx context.Context, in *RoomUserCountReq, opts ...grpc.CallOption) (*RoomUserCountResp, error)
}

type cometClient struct {
	cc *grpc.ClientConn
}

func NewCometClient(cc *grpc.ClientConn) CometClient {
	return &cometClient{cc}
}

func (c *cometClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) Close(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgReply, error) {
	out := new(PushMsgReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/PushMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) Broadcast(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*BroadcastReply, error) {
	out := new(BroadcastReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) BroadcastRoom(ctx context.Context, in *BroadcastRoomReq, opts ...grpc.CallOption) (*BroadcastRoomReply, error) {
	out := new(BroadcastRoomReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/BroadcastRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) Rooms(ctx context.Context, in *RoomsReq, opts ...grpc.CallOption) (*RoomsReply, error) {
	out := new(RoomsReply)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/Rooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) JoinRoom(ctx context.Context, in *JoinRoomReq, opts ...grpc.CallOption) (*JoinRoomeResp, error) {
	out := new(JoinRoomeResp)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/JoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) LeaveRoom(ctx context.Context, in *LeaveRoomReq, opts ...grpc.CallOption) (*LeaveRoomResp, error) {
	out := new(LeaveRoomResp)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/LeaveRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) CancelRoom(ctx context.Context, in *CancelRoomReq, opts ...grpc.CallOption) (*CancelRoomResp, error) {
	out := new(CancelRoomResp)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/CancelRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) RoomInfolRoom(ctx context.Context, in *RoomInfoReq, opts ...grpc.CallOption) (*RoomInfoResp, error) {
	out := new(RoomInfoResp)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/RoomInfolRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) JoinRooms(ctx context.Context, in *JoinRoomsReq, opts ...grpc.CallOption) (*JoinRoomesResp, error) {
	out := new(JoinRoomesResp)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/JoinRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) RoomUserCount(ctx context.Context, in *RoomUserCountReq, opts ...grpc.CallOption) (*RoomUserCountResp, error) {
	out := new(RoomUserCountResp)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/RoomUserCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometClient) VeeGebruikerSessieUit(ctx context.Context, in *RoomUserCountReq, opts ...grpc.CallOption) (*RoomUserCountResp, error) {
	out := new(RoomUserCountResp)
	err := c.cc.Invoke(ctx, "/goim.comet.Comet/VeeGebruikerSessieUit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CometServer is the server API for Comet service.
type CometServer interface {
	// Ping Service
	Ping(context.Context, *Empty) (*Empty, error)
	// Close Service
	Close(context.Context, *Empty) (*Empty, error)
	//PushMsg push by key or mid
	PushMsg(context.Context, *PushMsgReq) (*PushMsgReply, error)
	// Broadcast send to every enrity
	Broadcast(context.Context, *BroadcastReq) (*BroadcastReply, error)
	// BroadcastRoom broadcast to one room
	BroadcastRoom(context.Context, *BroadcastRoomReq) (*BroadcastRoomReply, error)
	// Rooms get all rooms
	Rooms(context.Context, *RoomsReq) (*RoomsReply, error)
	// 进入房间
	JoinRoom(context.Context, *JoinRoomReq) (*JoinRoomeResp, error)
	// 退出房间
	LeaveRoom(context.Context, *LeaveRoomReq) (*LeaveRoomResp, error)
	// 注销房间
	CancelRoom(context.Context, *CancelRoomReq) (*CancelRoomResp, error)
	// 房间信息
	RoomInfolRoom(context.Context, *RoomInfoReq) (*RoomInfoResp, error)
	// 进入多房间
	JoinRooms(context.Context, *JoinRoomsReq) (*JoinRoomesResp, error)
	// 房间人数
	RoomUserCount(context.Context, *RoomUserCountReq) (*RoomUserCountResp, error)
	// 接收人是否在线
	VeeGebruikerSessieUit(context.Context, *RoomUserCountReq) (*RoomUserCountResp, error)
}

// UnimplementedCometServer can be embedded to have forward compatible implementations.
type UnimplementedCometServer struct {
}

func (*UnimplementedCometServer) Ping(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedCometServer) Close(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (*UnimplementedCometServer) PushMsg(ctx context.Context, req *PushMsgReq) (*PushMsgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMsg not implemented")
}
func (*UnimplementedCometServer) Broadcast(ctx context.Context, req *BroadcastReq) (*BroadcastReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (*UnimplementedCometServer) BroadcastRoom(ctx context.Context, req *BroadcastRoomReq) (*BroadcastRoomReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastRoom not implemented")
}
func (*UnimplementedCometServer) Rooms(ctx context.Context, req *RoomsReq) (*RoomsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rooms not implemented")
}
func (*UnimplementedCometServer) JoinRoom(ctx context.Context, req *JoinRoomReq) (*JoinRoomeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}
func (*UnimplementedCometServer) LeaveRoom(ctx context.Context, req *LeaveRoomReq) (*LeaveRoomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveRoom not implemented")
}
func (*UnimplementedCometServer) CancelRoom(ctx context.Context, req *CancelRoomReq) (*CancelRoomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRoom not implemented")
}
func (*UnimplementedCometServer) RoomInfolRoom(ctx context.Context, req *RoomInfoReq) (*RoomInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoomInfolRoom not implemented")
}
func (*UnimplementedCometServer) JoinRooms(ctx context.Context, req *JoinRoomsReq) (*JoinRoomesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRooms not implemented")
}
func (*UnimplementedCometServer) RoomUserCount(ctx context.Context, req *RoomUserCountReq) (*RoomUserCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoomUserCount not implemented")
}
func (*UnimplementedCometServer) VeeGebruikerSessieUit(ctx context.Context, req *RoomUserCountReq) (*RoomUserCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VeeGebruikerSessieUit not implemented")
}

func RegisterCometServer(s *grpc.Server, srv CometServer) {
	s.RegisterService(&_Comet_serviceDesc, srv)
}

func _Comet_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Close(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/PushMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).PushMsg(ctx, req.(*PushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Broadcast(ctx, req.(*BroadcastReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_BroadcastRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).BroadcastRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/BroadcastRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).BroadcastRoom(ctx, req.(*BroadcastRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_Rooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).Rooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/Rooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).Rooms(ctx, req.(*RoomsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).JoinRoom(ctx, req.(*JoinRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/LeaveRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).LeaveRoom(ctx, req.(*LeaveRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_CancelRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).CancelRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/CancelRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).CancelRoom(ctx, req.(*CancelRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_RoomInfolRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).RoomInfolRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/RoomInfolRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).RoomInfolRoom(ctx, req.(*RoomInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_JoinRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).JoinRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/JoinRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).JoinRooms(ctx, req.(*JoinRoomsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_RoomUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomUserCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).RoomUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/RoomUserCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).RoomUserCount(ctx, req.(*RoomUserCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comet_VeeGebruikerSessieUit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomUserCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).VeeGebruikerSessieUit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.comet.Comet/VeeGebruikerSessieUit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).VeeGebruikerSessieUit(ctx, req.(*RoomUserCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goim.comet.Comet",
	HandlerType: (*CometServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Comet_Ping_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Comet_Close_Handler,
		},
		{
			MethodName: "PushMsg",
			Handler:    _Comet_PushMsg_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _Comet_Broadcast_Handler,
		},
		{
			MethodName: "BroadcastRoom",
			Handler:    _Comet_BroadcastRoom_Handler,
		},
		{
			MethodName: "Rooms",
			Handler:    _Comet_Rooms_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _Comet_JoinRoom_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _Comet_LeaveRoom_Handler,
		},
		{
			MethodName: "CancelRoom",
			Handler:    _Comet_CancelRoom_Handler,
		},
		{
			MethodName: "RoomInfolRoom",
			Handler:    _Comet_RoomInfolRoom_Handler,
		},
		{
			MethodName: "JoinRooms",
			Handler:    _Comet_JoinRooms_Handler,
		},
		{
			MethodName: "RoomUserCount",
			Handler:    _Comet_RoomUserCount_Handler,
		},
		{
			MethodName: "VeeGebruikerSessieUit",
			Handler:    _Comet_VeeGebruikerSessieUit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
