// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package grpc

import (
	grpc "baseGo/src/imserver/api/comet/grpc"
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc1 "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushMsg_Type int32

const (
	PushMsg_PUSH      PushMsg_Type = 0
	PushMsg_ROOM      PushMsg_Type = 1
	PushMsg_BROADCAST PushMsg_Type = 2
)

var PushMsg_Type_name = map[int32]string{
	0: "PUSH",
	1: "ROOM",
	2: "BROADCAST",
}

var PushMsg_Type_value = map[string]int32{
	"PUSH":      0,
	"ROOM":      1,
	"BROADCAST": 2,
}

func (x PushMsg_Type) String() string {
	return proto.EnumName(PushMsg_Type_name, int32(x))
}

func (PushMsg_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0}
}

type PushMsg_IsDel int32

const (
	PushMsg_NO  PushMsg_IsDel = 0
	PushMsg_YES PushMsg_IsDel = 1
)

var PushMsg_IsDel_name = map[int32]string{
	0: "NO",
	1: "YES",
}

var PushMsg_IsDel_value = map[string]int32{
	"NO":  0,
	"YES": 1,
}

func (x PushMsg_IsDel) String() string {
	return proto.EnumName(PushMsg_IsDel_name, int32(x))
}

func (PushMsg_IsDel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 1}
}

type PushMsg struct {
	// 发送类型
	Type PushMsg_Type `protobuf:"varint,1,opt,name=type,proto3,enum=goim.logic.PushMsg_Type" json:"type,omitempty"`
	// 操作类型
	Operation int32 `protobuf:"varint,2,opt,name=operation,proto3" json:"operation,omitempty"`
	// 房间id
	RoomId int32 `protobuf:"varint,3,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	// 发送人id
	Mid int32 `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	// 发送时间
	SendTime int32         `protobuf:"varint,5,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	MsgType  int32         `protobuf:"varint,6,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Msg      []byte        `protobuf:"bytes,7,opt,name=Msg,proto3" json:"Msg,omitempty"`
	IsDel    PushMsg_IsDel `protobuf:"varint,8,opt,name=isDel,proto3,enum=goim.logic.PushMsg_IsDel" json:"isDel,omitempty"`
	MsgId    int32         `protobuf:"varint,9,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Speed    int32         `protobuf:"varint,10,opt,name=speed,proto3" json:"speed,omitempty"`
	Server   string        `protobuf:"bytes,11,opt,name=server,proto3" json:"server,omitempty"`
	// 接收人
	ReceiverId           int32    `protobuf:"varint,12,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	SenderName           string   `protobuf:"bytes,13,opt,name=senderName,proto3" json:"senderName,omitempty"`
	SenderHead           string   `protobuf:"bytes,14,opt,name=senderHead,proto3" json:"senderHead,omitempty"`
	SenderLevel          int64    `protobuf:"varint,15,opt,name=senderLevel,proto3" json:"senderLevel,omitempty"`
	SenderLevelPhoto     string   `protobuf:"bytes,16,opt,name=senderLevelPhoto,proto3" json:"senderLevelPhoto,omitempty"`
	ReceiveType          int32    `protobuf:"varint,17,opt,name=receiveType,proto3" json:"receiveType,omitempty"`
	Account              string   `protobuf:"bytes,18,opt,name=account,proto3" json:"account,omitempty"`
	LineId               string   `protobuf:"bytes,19,opt,name=lineId,proto3" json:"lineId,omitempty"`
	AgencyId             string   `protobuf:"bytes,20,opt,name=agencyId,proto3" json:"agencyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsg) Reset()         { *m = PushMsg{} }
func (m *PushMsg) String() string { return proto.CompactTextString(m) }
func (*PushMsg) ProtoMessage()    {}
func (*PushMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PushMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsg.Unmarshal(m, b)
}
func (m *PushMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsg.Marshal(b, m, deterministic)
}
func (m *PushMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsg.Merge(m, src)
}
func (m *PushMsg) XXX_Size() int {
	return xxx_messageInfo_PushMsg.Size(m)
}
func (m *PushMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsg proto.InternalMessageInfo

func (m *PushMsg) GetType() PushMsg_Type {
	if m != nil {
		return m.Type
	}
	return PushMsg_PUSH
}

func (m *PushMsg) GetOperation() int32 {
	if m != nil {
		return m.Operation
	}
	return 0
}

func (m *PushMsg) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *PushMsg) GetMid() int32 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *PushMsg) GetSendTime() int32 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *PushMsg) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *PushMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *PushMsg) GetIsDel() PushMsg_IsDel {
	if m != nil {
		return m.IsDel
	}
	return PushMsg_NO
}

func (m *PushMsg) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *PushMsg) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *PushMsg) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *PushMsg) GetReceiverId() int32 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *PushMsg) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *PushMsg) GetSenderHead() string {
	if m != nil {
		return m.SenderHead
	}
	return ""
}

func (m *PushMsg) GetSenderLevel() int64 {
	if m != nil {
		return m.SenderLevel
	}
	return 0
}

func (m *PushMsg) GetSenderLevelPhoto() string {
	if m != nil {
		return m.SenderLevelPhoto
	}
	return ""
}

func (m *PushMsg) GetReceiveType() int32 {
	if m != nil {
		return m.ReceiveType
	}
	return 0
}

func (m *PushMsg) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *PushMsg) GetLineId() string {
	if m != nil {
		return m.LineId
	}
	return ""
}

func (m *PushMsg) GetAgencyId() string {
	if m != nil {
		return m.AgencyId
	}
	return ""
}

type CloseReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseReply) Reset()         { *m = CloseReply{} }
func (m *CloseReply) String() string { return proto.CompactTextString(m) }
func (*CloseReply) ProtoMessage()    {}
func (*CloseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CloseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseReply.Unmarshal(m, b)
}
func (m *CloseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseReply.Marshal(b, m, deterministic)
}
func (m *CloseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseReply.Merge(m, src)
}
func (m *CloseReply) XXX_Size() int {
	return xxx_messageInfo_CloseReply.Size(m)
}
func (m *CloseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseReply.DiscardUnknown(m)
}

var xxx_messageInfo_CloseReply proto.InternalMessageInfo

type CloseReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseReq) Reset()         { *m = CloseReq{} }
func (m *CloseReq) String() string { return proto.CompactTextString(m) }
func (*CloseReq) ProtoMessage()    {}
func (*CloseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *CloseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseReq.Unmarshal(m, b)
}
func (m *CloseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseReq.Marshal(b, m, deterministic)
}
func (m *CloseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseReq.Merge(m, src)
}
func (m *CloseReq) XXX_Size() int {
	return xxx_messageInfo_CloseReq.Size(m)
}
func (m *CloseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseReq.DiscardUnknown(m)
}

var xxx_messageInfo_CloseReq proto.InternalMessageInfo

type PingReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (m *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(m, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

type PingReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

type ConnectReq struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Cookie               string   `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Token                []byte   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectReq) Reset()         { *m = ConnectReq{} }
func (m *ConnectReq) String() string { return proto.CompactTextString(m) }
func (*ConnectReq) ProtoMessage()    {}
func (*ConnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *ConnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectReq.Unmarshal(m, b)
}
func (m *ConnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectReq.Marshal(b, m, deterministic)
}
func (m *ConnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectReq.Merge(m, src)
}
func (m *ConnectReq) XXX_Size() int {
	return xxx_messageInfo_ConnectReq.Size(m)
}
func (m *ConnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectReq proto.InternalMessageInfo

func (m *ConnectReq) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *ConnectReq) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

func (m *ConnectReq) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type ConnectReply struct {
	Mid                  int64    `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	RoomID               string   `protobuf:"bytes,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Accepts              []int32  `protobuf:"varint,4,rep,packed,name=accepts,proto3" json:"accepts,omitempty"`
	Heartbeat            int64    `protobuf:"varint,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectReply) Reset()         { *m = ConnectReply{} }
func (m *ConnectReply) String() string { return proto.CompactTextString(m) }
func (*ConnectReply) ProtoMessage()    {}
func (*ConnectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *ConnectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectReply.Unmarshal(m, b)
}
func (m *ConnectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectReply.Marshal(b, m, deterministic)
}
func (m *ConnectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectReply.Merge(m, src)
}
func (m *ConnectReply) XXX_Size() int {
	return xxx_messageInfo_ConnectReply.Size(m)
}
func (m *ConnectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectReply proto.InternalMessageInfo

func (m *ConnectReply) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *ConnectReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConnectReply) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *ConnectReply) GetAccepts() []int32 {
	if m != nil {
		return m.Accepts
	}
	return nil
}

func (m *ConnectReply) GetHeartbeat() int64 {
	if m != nil {
		return m.Heartbeat
	}
	return 0
}

type DisconnectReq struct {
	Mid                  int64    `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Server               string   `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectReq) Reset()         { *m = DisconnectReq{} }
func (m *DisconnectReq) String() string { return proto.CompactTextString(m) }
func (*DisconnectReq) ProtoMessage()    {}
func (*DisconnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *DisconnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectReq.Unmarshal(m, b)
}
func (m *DisconnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectReq.Marshal(b, m, deterministic)
}
func (m *DisconnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectReq.Merge(m, src)
}
func (m *DisconnectReq) XXX_Size() int {
	return xxx_messageInfo_DisconnectReq.Size(m)
}
func (m *DisconnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectReq proto.InternalMessageInfo

func (m *DisconnectReq) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *DisconnectReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DisconnectReq) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type DisconnectReply struct {
	Has                  bool     `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectReply) Reset()         { *m = DisconnectReply{} }
func (m *DisconnectReply) String() string { return proto.CompactTextString(m) }
func (*DisconnectReply) ProtoMessage()    {}
func (*DisconnectReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *DisconnectReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectReply.Unmarshal(m, b)
}
func (m *DisconnectReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectReply.Marshal(b, m, deterministic)
}
func (m *DisconnectReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectReply.Merge(m, src)
}
func (m *DisconnectReply) XXX_Size() int {
	return xxx_messageInfo_DisconnectReply.Size(m)
}
func (m *DisconnectReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectReply.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectReply proto.InternalMessageInfo

func (m *DisconnectReply) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

type HeartbeatReq struct {
	Mid                  int64    `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Server               string   `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatReq) Reset()         { *m = HeartbeatReq{} }
func (m *HeartbeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartbeatReq) ProtoMessage()    {}
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *HeartbeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatReq.Unmarshal(m, b)
}
func (m *HeartbeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatReq.Marshal(b, m, deterministic)
}
func (m *HeartbeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatReq.Merge(m, src)
}
func (m *HeartbeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartbeatReq.Size(m)
}
func (m *HeartbeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatReq proto.InternalMessageInfo

func (m *HeartbeatReq) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *HeartbeatReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HeartbeatReq) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type HeartbeatReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatReply) Reset()         { *m = HeartbeatReply{} }
func (m *HeartbeatReply) String() string { return proto.CompactTextString(m) }
func (*HeartbeatReply) ProtoMessage()    {}
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *HeartbeatReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatReply.Unmarshal(m, b)
}
func (m *HeartbeatReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatReply.Marshal(b, m, deterministic)
}
func (m *HeartbeatReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatReply.Merge(m, src)
}
func (m *HeartbeatReply) XXX_Size() int {
	return xxx_messageInfo_HeartbeatReply.Size(m)
}
func (m *HeartbeatReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatReply.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatReply proto.InternalMessageInfo

type OnlineReq struct {
	Server               string           `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	RoomCount            map[string]int32 `protobuf:"bytes,2,rep,name=roomCount,proto3" json:"roomCount,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OnlineReq) Reset()         { *m = OnlineReq{} }
func (m *OnlineReq) String() string { return proto.CompactTextString(m) }
func (*OnlineReq) ProtoMessage()    {}
func (*OnlineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *OnlineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineReq.Unmarshal(m, b)
}
func (m *OnlineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineReq.Marshal(b, m, deterministic)
}
func (m *OnlineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineReq.Merge(m, src)
}
func (m *OnlineReq) XXX_Size() int {
	return xxx_messageInfo_OnlineReq.Size(m)
}
func (m *OnlineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineReq.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineReq proto.InternalMessageInfo

func (m *OnlineReq) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *OnlineReq) GetRoomCount() map[string]int32 {
	if m != nil {
		return m.RoomCount
	}
	return nil
}

type OnlineReply struct {
	AllRoomCount         map[string]int32 `protobuf:"bytes,1,rep,name=allRoomCount,proto3" json:"allRoomCount,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OnlineReply) Reset()         { *m = OnlineReply{} }
func (m *OnlineReply) String() string { return proto.CompactTextString(m) }
func (*OnlineReply) ProtoMessage()    {}
func (*OnlineReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *OnlineReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineReply.Unmarshal(m, b)
}
func (m *OnlineReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineReply.Marshal(b, m, deterministic)
}
func (m *OnlineReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineReply.Merge(m, src)
}
func (m *OnlineReply) XXX_Size() int {
	return xxx_messageInfo_OnlineReply.Size(m)
}
func (m *OnlineReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineReply.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineReply proto.InternalMessageInfo

func (m *OnlineReply) GetAllRoomCount() map[string]int32 {
	if m != nil {
		return m.AllRoomCount
	}
	return nil
}

type ReceiveReq struct {
	Mid                  int64       `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Proto                *grpc.Proto `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReceiveReq) Reset()         { *m = ReceiveReq{} }
func (m *ReceiveReq) String() string { return proto.CompactTextString(m) }
func (*ReceiveReq) ProtoMessage()    {}
func (*ReceiveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *ReceiveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveReq.Unmarshal(m, b)
}
func (m *ReceiveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveReq.Marshal(b, m, deterministic)
}
func (m *ReceiveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveReq.Merge(m, src)
}
func (m *ReceiveReq) XXX_Size() int {
	return xxx_messageInfo_ReceiveReq.Size(m)
}
func (m *ReceiveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveReq proto.InternalMessageInfo

func (m *ReceiveReq) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *ReceiveReq) GetProto() *grpc.Proto {
	if m != nil {
		return m.Proto
	}
	return nil
}

type ReceiveReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveReply) Reset()         { *m = ReceiveReply{} }
func (m *ReceiveReply) String() string { return proto.CompactTextString(m) }
func (*ReceiveReply) ProtoMessage()    {}
func (*ReceiveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *ReceiveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveReply.Unmarshal(m, b)
}
func (m *ReceiveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveReply.Marshal(b, m, deterministic)
}
func (m *ReceiveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveReply.Merge(m, src)
}
func (m *ReceiveReply) XXX_Size() int {
	return xxx_messageInfo_ReceiveReply.Size(m)
}
func (m *ReceiveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveReply proto.InternalMessageInfo

type NodesReq struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ClientIP             string   `protobuf:"bytes,2,opt,name=clientIP,proto3" json:"clientIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodesReq) Reset()         { *m = NodesReq{} }
func (m *NodesReq) String() string { return proto.CompactTextString(m) }
func (*NodesReq) ProtoMessage()    {}
func (*NodesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *NodesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesReq.Unmarshal(m, b)
}
func (m *NodesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesReq.Marshal(b, m, deterministic)
}
func (m *NodesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesReq.Merge(m, src)
}
func (m *NodesReq) XXX_Size() int {
	return xxx_messageInfo_NodesReq.Size(m)
}
func (m *NodesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesReq.DiscardUnknown(m)
}

var xxx_messageInfo_NodesReq proto.InternalMessageInfo

func (m *NodesReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *NodesReq) GetClientIP() string {
	if m != nil {
		return m.ClientIP
	}
	return ""
}

type NodesReply struct {
	Domain               string   `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	TcpPort              int32    `protobuf:"varint,2,opt,name=tcpPort,proto3" json:"tcpPort,omitempty"`
	WsPort               int32    `protobuf:"varint,3,opt,name=wsPort,proto3" json:"wsPort,omitempty"`
	WssPort              int32    `protobuf:"varint,4,opt,name=wssPort,proto3" json:"wssPort,omitempty"`
	Heartbeat            int32    `protobuf:"varint,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Nodes                []string `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Backoff              *Backoff `protobuf:"bytes,7,opt,name=backoff,proto3" json:"backoff,omitempty"`
	HeartbeatMax         int32    `protobuf:"varint,8,opt,name=heartbeatMax,proto3" json:"heartbeatMax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodesReply) Reset()         { *m = NodesReply{} }
func (m *NodesReply) String() string { return proto.CompactTextString(m) }
func (*NodesReply) ProtoMessage()    {}
func (*NodesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *NodesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesReply.Unmarshal(m, b)
}
func (m *NodesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesReply.Marshal(b, m, deterministic)
}
func (m *NodesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesReply.Merge(m, src)
}
func (m *NodesReply) XXX_Size() int {
	return xxx_messageInfo_NodesReply.Size(m)
}
func (m *NodesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesReply.DiscardUnknown(m)
}

var xxx_messageInfo_NodesReply proto.InternalMessageInfo

func (m *NodesReply) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *NodesReply) GetTcpPort() int32 {
	if m != nil {
		return m.TcpPort
	}
	return 0
}

func (m *NodesReply) GetWsPort() int32 {
	if m != nil {
		return m.WsPort
	}
	return 0
}

func (m *NodesReply) GetWssPort() int32 {
	if m != nil {
		return m.WssPort
	}
	return 0
}

func (m *NodesReply) GetHeartbeat() int32 {
	if m != nil {
		return m.Heartbeat
	}
	return 0
}

func (m *NodesReply) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *NodesReply) GetBackoff() *Backoff {
	if m != nil {
		return m.Backoff
	}
	return nil
}

func (m *NodesReply) GetHeartbeatMax() int32 {
	if m != nil {
		return m.HeartbeatMax
	}
	return 0
}

type Backoff struct {
	MaxDelay             int32    `protobuf:"varint,1,opt,name=MaxDelay,proto3" json:"MaxDelay,omitempty"`
	BaseDelay            int32    `protobuf:"varint,2,opt,name=BaseDelay,proto3" json:"BaseDelay,omitempty"`
	Factor               float32  `protobuf:"fixed32,3,opt,name=Factor,proto3" json:"Factor,omitempty"`
	Jitter               float32  `protobuf:"fixed32,4,opt,name=Jitter,proto3" json:"Jitter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Backoff) Reset()         { *m = Backoff{} }
func (m *Backoff) String() string { return proto.CompactTextString(m) }
func (*Backoff) ProtoMessage()    {}
func (*Backoff) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *Backoff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backoff.Unmarshal(m, b)
}
func (m *Backoff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backoff.Marshal(b, m, deterministic)
}
func (m *Backoff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backoff.Merge(m, src)
}
func (m *Backoff) XXX_Size() int {
	return xxx_messageInfo_Backoff.Size(m)
}
func (m *Backoff) XXX_DiscardUnknown() {
	xxx_messageInfo_Backoff.DiscardUnknown(m)
}

var xxx_messageInfo_Backoff proto.InternalMessageInfo

func (m *Backoff) GetMaxDelay() int32 {
	if m != nil {
		return m.MaxDelay
	}
	return 0
}

func (m *Backoff) GetBaseDelay() int32 {
	if m != nil {
		return m.BaseDelay
	}
	return 0
}

func (m *Backoff) GetFactor() float32 {
	if m != nil {
		return m.Factor
	}
	return 0
}

func (m *Backoff) GetJitter() float32 {
	if m != nil {
		return m.Jitter
	}
	return 0
}

type JoinRoomReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Base                 *Base    `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomReq) Reset()         { *m = JoinRoomReq{} }
func (m *JoinRoomReq) String() string { return proto.CompactTextString(m) }
func (*JoinRoomReq) ProtoMessage()    {}
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *JoinRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomReq.Unmarshal(m, b)
}
func (m *JoinRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomReq.Marshal(b, m, deterministic)
}
func (m *JoinRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomReq.Merge(m, src)
}
func (m *JoinRoomReq) XXX_Size() int {
	return xxx_messageInfo_JoinRoomReq.Size(m)
}
func (m *JoinRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomReq proto.InternalMessageInfo

func (m *JoinRoomReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *JoinRoomReq) GetBase() *Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type JoinRoomeResp struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Tokken               string   `protobuf:"bytes,2,opt,name=tokken,proto3" json:"tokken,omitempty"`
	RoomID               string   `protobuf:"bytes,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Rooms                []string `protobuf:"bytes,4,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomeResp) Reset()         { *m = JoinRoomeResp{} }
func (m *JoinRoomeResp) String() string { return proto.CompactTextString(m) }
func (*JoinRoomeResp) ProtoMessage()    {}
func (*JoinRoomeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *JoinRoomeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomeResp.Unmarshal(m, b)
}
func (m *JoinRoomeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomeResp.Marshal(b, m, deterministic)
}
func (m *JoinRoomeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomeResp.Merge(m, src)
}
func (m *JoinRoomeResp) XXX_Size() int {
	return xxx_messageInfo_JoinRoomeResp.Size(m)
}
func (m *JoinRoomeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomeResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomeResp proto.InternalMessageInfo

func (m *JoinRoomeResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *JoinRoomeResp) GetTokken() string {
	if m != nil {
		return m.Tokken
	}
	return ""
}

func (m *JoinRoomeResp) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *JoinRoomeResp) GetRooms() []string {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type Base struct {
	Tokken               string   `protobuf:"bytes,1,opt,name=tokken,proto3" json:"tokken,omitempty"`
	Server               string   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	LineId               string   `protobuf:"bytes,3,opt,name=lineId,proto3" json:"lineId,omitempty"`
	AgencyId             string   `protobuf:"bytes,4,opt,name=agencyId,proto3" json:"agencyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Base) Reset()         { *m = Base{} }
func (m *Base) String() string { return proto.CompactTextString(m) }
func (*Base) ProtoMessage()    {}
func (*Base) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *Base) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Base.Unmarshal(m, b)
}
func (m *Base) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Base.Marshal(b, m, deterministic)
}
func (m *Base) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Base.Merge(m, src)
}
func (m *Base) XXX_Size() int {
	return xxx_messageInfo_Base.Size(m)
}
func (m *Base) XXX_DiscardUnknown() {
	xxx_messageInfo_Base.DiscardUnknown(m)
}

var xxx_messageInfo_Base proto.InternalMessageInfo

func (m *Base) GetTokken() string {
	if m != nil {
		return m.Tokken
	}
	return ""
}

func (m *Base) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Base) GetLineId() string {
	if m != nil {
		return m.LineId
	}
	return ""
}

func (m *Base) GetAgencyId() string {
	if m != nil {
		return m.AgencyId
	}
	return ""
}

type EstablishConnReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Base                 *Base    `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstablishConnReq) Reset()         { *m = EstablishConnReq{} }
func (m *EstablishConnReq) String() string { return proto.CompactTextString(m) }
func (*EstablishConnReq) ProtoMessage()    {}
func (*EstablishConnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *EstablishConnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishConnReq.Unmarshal(m, b)
}
func (m *EstablishConnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishConnReq.Marshal(b, m, deterministic)
}
func (m *EstablishConnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishConnReq.Merge(m, src)
}
func (m *EstablishConnReq) XXX_Size() int {
	return xxx_messageInfo_EstablishConnReq.Size(m)
}
func (m *EstablishConnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishConnReq.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishConnReq proto.InternalMessageInfo

func (m *EstablishConnReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *EstablishConnReq) GetBase() *Base {
	if m != nil {
		return m.Base
	}
	return nil
}

type EstablishConnResp struct {
	Mid                  int64    `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	RoomID               string   `protobuf:"bytes,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Accepts              []int32  `protobuf:"varint,4,rep,packed,name=accepts,proto3" json:"accepts,omitempty"`
	Heartbeat            int64    `protobuf:"varint,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Result               bool     `protobuf:"varint,6,opt,name=result,proto3" json:"result,omitempty"`
	Rooms                []string `protobuf:"bytes,7,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EstablishConnResp) Reset()         { *m = EstablishConnResp{} }
func (m *EstablishConnResp) String() string { return proto.CompactTextString(m) }
func (*EstablishConnResp) ProtoMessage()    {}
func (*EstablishConnResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *EstablishConnResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstablishConnResp.Unmarshal(m, b)
}
func (m *EstablishConnResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstablishConnResp.Marshal(b, m, deterministic)
}
func (m *EstablishConnResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstablishConnResp.Merge(m, src)
}
func (m *EstablishConnResp) XXX_Size() int {
	return xxx_messageInfo_EstablishConnResp.Size(m)
}
func (m *EstablishConnResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EstablishConnResp.DiscardUnknown(m)
}

var xxx_messageInfo_EstablishConnResp proto.InternalMessageInfo

func (m *EstablishConnResp) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *EstablishConnResp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EstablishConnResp) GetRoomID() string {
	if m != nil {
		return m.RoomID
	}
	return ""
}

func (m *EstablishConnResp) GetAccepts() []int32 {
	if m != nil {
		return m.Accepts
	}
	return nil
}

func (m *EstablishConnResp) GetHeartbeat() int64 {
	if m != nil {
		return m.Heartbeat
	}
	return 0
}

func (m *EstablishConnResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *EstablishConnResp) GetRooms() []string {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func init() {
	proto.RegisterEnum("goim.logic.PushMsg_Type", PushMsg_Type_name, PushMsg_Type_value)
	proto.RegisterEnum("goim.logic.PushMsg_IsDel", PushMsg_IsDel_name, PushMsg_IsDel_value)
	proto.RegisterType((*PushMsg)(nil), "goim.logic.PushMsg")
	proto.RegisterType((*CloseReply)(nil), "goim.logic.CloseReply")
	proto.RegisterType((*CloseReq)(nil), "goim.logic.CloseReq")
	proto.RegisterType((*PingReply)(nil), "goim.logic.PingReply")
	proto.RegisterType((*PingReq)(nil), "goim.logic.PingReq")
	proto.RegisterType((*ConnectReq)(nil), "goim.logic.ConnectReq")
	proto.RegisterType((*ConnectReply)(nil), "goim.logic.ConnectReply")
	proto.RegisterType((*DisconnectReq)(nil), "goim.logic.DisconnectReq")
	proto.RegisterType((*DisconnectReply)(nil), "goim.logic.DisconnectReply")
	proto.RegisterType((*HeartbeatReq)(nil), "goim.logic.HeartbeatReq")
	proto.RegisterType((*HeartbeatReply)(nil), "goim.logic.HeartbeatReply")
	proto.RegisterType((*OnlineReq)(nil), "goim.logic.OnlineReq")
	proto.RegisterMapType((map[string]int32)(nil), "goim.logic.OnlineReq.RoomCountEntry")
	proto.RegisterType((*OnlineReply)(nil), "goim.logic.OnlineReply")
	proto.RegisterMapType((map[string]int32)(nil), "goim.logic.OnlineReply.AllRoomCountEntry")
	proto.RegisterType((*ReceiveReq)(nil), "goim.logic.ReceiveReq")
	proto.RegisterType((*ReceiveReply)(nil), "goim.logic.ReceiveReply")
	proto.RegisterType((*NodesReq)(nil), "goim.logic.NodesReq")
	proto.RegisterType((*NodesReply)(nil), "goim.logic.NodesReply")
	proto.RegisterType((*Backoff)(nil), "goim.logic.Backoff")
	proto.RegisterType((*JoinRoomReq)(nil), "goim.logic.JoinRoomReq")
	proto.RegisterType((*JoinRoomeResp)(nil), "goim.logic.JoinRoomeResp")
	proto.RegisterType((*Base)(nil), "goim.logic.Base")
	proto.RegisterType((*EstablishConnReq)(nil), "goim.logic.EstablishConnReq")
	proto.RegisterType((*EstablishConnResp)(nil), "goim.logic.EstablishConnResp")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0x0e, 0x25, 0x51, 0x12, 0x8f, 0x64, 0x47, 0x9e, 0x38, 0xb9, 0x0c, 0x6f, 0xee, 0x95, 0x2e,
	0x13, 0xdc, 0x3a, 0x6d, 0x2a, 0x01, 0x2e, 0x02, 0x14, 0xe9, 0x1f, 0x2c, 0x3b, 0x6d, 0x94, 0x44,
	0xb1, 0x30, 0x49, 0x81, 0xb6, 0x9b, 0x80, 0xa2, 0xc6, 0x32, 0x63, 0x92, 0xc3, 0x70, 0x28, 0xdb,
	0xda, 0xf6, 0x29, 0xba, 0x6b, 0x81, 0xee, 0xda, 0x75, 0x5f, 0x47, 0xcb, 0x2e, 0xf4, 0x06, 0xdd,
	0x15, 0xf3, 0x43, 0x8a, 0x74, 0xe4, 0xa0, 0x68, 0x16, 0x5d, 0x69, 0xce, 0xcf, 0x7c, 0x73, 0xe6,
	0x9c, 0x33, 0xe7, 0xa3, 0xc0, 0x70, 0x22, 0xaf, 0x1b, 0xc5, 0x34, 0xa1, 0x08, 0xa6, 0xd4, 0x0b,
	0xba, 0x3e, 0x9d, 0x7a, 0xae, 0xf5, 0x3f, 0x2f, 0x60, 0x24, 0x3e, 0x25, 0x71, 0xcf, 0x89, 0xbc,
	0x9e, 0x4b, 0x03, 0x92, 0xf4, 0xa6, 0x71, 0xe4, 0xf6, 0x32, 0x77, 0xeb, 0xc3, 0xa9, 0x97, 0x1c,
	0xcf, 0xc6, 0x5d, 0x97, 0x06, 0xbd, 0x29, 0x9d, 0xd2, 0x9e, 0x50, 0x8f, 0x67, 0x47, 0x42, 0x12,
	0x82, 0x58, 0x49, 0x77, 0xfb, 0x47, 0x1d, 0x6a, 0xa3, 0x19, 0x3b, 0x1e, 0xb2, 0x29, 0xba, 0x07,
	0x95, 0x64, 0x1e, 0x11, 0x53, 0xeb, 0x68, 0x3b, 0x9b, 0xbb, 0x66, 0x77, 0x75, 0x70, 0x57, 0xb9,
	0x74, 0x5f, 0xcc, 0x23, 0x82, 0x85, 0x17, 0xba, 0x05, 0x06, 0x8d, 0x48, 0xec, 0x24, 0x1e, 0x0d,
	0xcd, 0x52, 0x47, 0xdb, 0xd1, 0xf1, 0x4a, 0x81, 0x6e, 0x40, 0x15, 0x53, 0x1a, 0x0c, 0x26, 0x66,
	0x59, 0x98, 0x94, 0x84, 0x5a, 0x50, 0x0e, 0xbc, 0x89, 0x59, 0x11, 0x4a, 0xbe, 0x44, 0x16, 0xd4,
	0x19, 0x09, 0x27, 0x2f, 0xbc, 0x80, 0x98, 0xba, 0x50, 0x67, 0x32, 0x32, 0xa1, 0x16, 0xb0, 0x29,
	0x3f, 0xd4, 0xac, 0x0a, 0x53, 0x2a, 0x72, 0x9c, 0x21, 0x9b, 0x9a, 0xb5, 0x8e, 0xb6, 0xd3, 0xc4,
	0x7c, 0x89, 0x7a, 0xa0, 0x7b, 0xec, 0x80, 0xf8, 0x66, 0x5d, 0x84, 0x7f, 0x73, 0x5d, 0xf8, 0x03,
	0xee, 0x80, 0xa5, 0x1f, 0xda, 0x06, 0x7d, 0xc8, 0xa6, 0x83, 0x89, 0x69, 0x08, 0x68, 0x29, 0x70,
	0x2d, 0x8b, 0x08, 0x99, 0x98, 0x20, 0xb5, 0x42, 0xe0, 0xd7, 0x91, 0x89, 0x37, 0x1b, 0x1d, 0x6d,
	0xc7, 0xc0, 0x4a, 0x42, 0xff, 0x05, 0x88, 0x89, 0x4b, 0xbc, 0x53, 0x12, 0x0f, 0x26, 0x66, 0x53,
	0x6c, 0xc9, 0x69, 0xb8, 0x9d, 0x5f, 0x86, 0xc4, 0xcf, 0x9c, 0x80, 0x98, 0x1b, 0x62, 0x6f, 0x4e,
	0xb3, 0xb2, 0x3f, 0x22, 0xce, 0xc4, 0xdc, 0xcc, 0xdb, 0xb9, 0x06, 0x75, 0xa0, 0x21, 0xa5, 0xa7,
	0xe4, 0x94, 0xf8, 0xe6, 0xd5, 0x8e, 0xb6, 0x53, 0xc6, 0x79, 0x15, 0x7a, 0x1f, 0x5a, 0x39, 0x71,
	0x74, 0x4c, 0x13, 0x6a, 0xb6, 0x04, 0xce, 0x1b, 0x7a, 0x8e, 0xa6, 0x62, 0x13, 0x29, 0xdd, 0x12,
	0xe1, 0xe6, 0x55, 0x3c, 0xe1, 0x8e, 0xeb, 0xd2, 0x59, 0x98, 0x98, 0x48, 0x80, 0xa4, 0x22, 0xcf,
	0x80, 0xef, 0x85, 0x64, 0x30, 0x31, 0xaf, 0xc9, 0x0c, 0x48, 0x89, 0x97, 0xcf, 0x99, 0x92, 0xd0,
	0x9d, 0x0f, 0x26, 0xe6, 0xb6, 0xb0, 0x64, 0xb2, 0x7d, 0x17, 0x2a, 0x02, 0xb5, 0x0e, 0x95, 0xd1,
	0xd7, 0xcf, 0x1f, 0xb5, 0xae, 0xf0, 0x15, 0x3e, 0x3c, 0x1c, 0xb6, 0x34, 0xb4, 0x01, 0x46, 0x1f,
	0x1f, 0xee, 0x1d, 0xec, 0xef, 0x3d, 0x7f, 0xd1, 0x2a, 0xd9, 0x26, 0xe8, 0xa2, 0x38, 0xa8, 0x0a,
	0xa5, 0x67, 0x87, 0xad, 0x2b, 0xa8, 0x06, 0xe5, 0x6f, 0x1f, 0x3e, 0x6f, 0x69, 0x76, 0x13, 0x60,
	0xdf, 0xa7, 0x8c, 0x60, 0x12, 0xf9, 0x73, 0x1b, 0xa0, 0xae, 0xa4, 0xd7, 0x76, 0x03, 0x8c, 0x91,
	0x17, 0x4e, 0xa5, 0xc1, 0x80, 0x9a, 0x14, 0x5e, 0xdb, 0xdf, 0x00, 0xec, 0xd3, 0x30, 0x24, 0x6e,
	0x82, 0xc9, 0xeb, 0x5c, 0xe9, 0xb4, 0x42, 0xe9, 0x6e, 0x40, 0xd5, 0xa5, 0xf4, 0xc4, 0x23, 0xa2,
	0x79, 0x0d, 0xac, 0x24, 0xde, 0x00, 0x09, 0x3d, 0x21, 0xa1, 0x68, 0xdc, 0x26, 0x96, 0xc2, 0x83,
	0xca, 0x0f, 0x3f, 0xb5, 0xaf, 0xd8, 0xdf, 0x6b, 0xd0, 0xcc, 0xa0, 0x23, 0x7f, 0x9e, 0xb6, 0xb3,
	0x26, 0xea, 0x22, 0xda, 0xb9, 0x05, 0xe5, 0x13, 0x32, 0x57, 0x98, 0x7c, 0xc9, 0x0f, 0x8a, 0x79,
	0xf3, 0x1f, 0x08, 0x44, 0x03, 0x2b, 0x49, 0xe5, 0x9a, 0x44, 0x09, 0x33, 0x2b, 0x9d, 0x32, 0x6f,
	0x6e, 0x25, 0xf2, 0xa7, 0x75, 0x4c, 0x9c, 0x38, 0x19, 0x13, 0x27, 0x11, 0x6f, 0xa2, 0x8c, 0x57,
	0x0a, 0xfb, 0x09, 0x6c, 0x1c, 0x78, 0xcc, 0x5d, 0xdd, 0xf0, 0x2f, 0x06, 0xa1, 0xb2, 0x50, 0xce,
	0x67, 0xc1, 0xbe, 0x0d, 0x57, 0xf3, 0x60, 0xea, 0x4e, 0xc7, 0x0e, 0x13, 0x70, 0x75, 0xcc, 0x97,
	0xf6, 0x63, 0x68, 0x3e, 0x4a, 0x8f, 0x7f, 0xd7, 0x03, 0x5b, 0xb0, 0x99, 0xc3, 0xe2, 0x95, 0xfb,
	0x55, 0x03, 0xe3, 0x30, 0xe4, 0xed, 0xf4, 0xb6, 0x72, 0xf5, 0xc1, 0xe0, 0x79, 0xdb, 0x17, 0xbd,
	0x59, 0xea, 0x94, 0x77, 0x1a, 0xbb, 0x77, 0xf2, 0x4f, 0x3c, 0x43, 0xe8, 0xe2, 0xd4, 0xed, 0x61,
	0x98, 0xc4, 0x73, 0xbc, 0xda, 0x66, 0x7d, 0x0a, 0x9b, 0x45, 0x63, 0x1a, 0xb7, 0xb6, 0x8a, 0x7b,
	0x1b, 0xf4, 0x53, 0xc7, 0x9f, 0x11, 0x35, 0xd2, 0xa4, 0xf0, 0xa0, 0xf4, 0xb1, 0xa6, 0x5a, 0xe0,
	0x67, 0x0d, 0x1a, 0xe9, 0x59, 0x3c, 0x5b, 0x43, 0x68, 0x3a, 0xbe, 0x9f, 0xc1, 0x9a, 0x9a, 0x08,
	0xed, 0xee, 0xba, 0xd0, 0x22, 0x7f, 0xde, 0xdd, 0xcb, 0xf9, 0xca, 0xf8, 0x0a, 0xdb, 0xad, 0x2f,
	0x60, 0xeb, 0x0d, 0x97, 0xbf, 0x11, 0xe5, 0x57, 0x00, 0x58, 0x3e, 0xeb, 0xf5, 0xf5, 0x7a, 0x0f,
	0x74, 0x31, 0xff, 0xc5, 0xfe, 0xc6, 0xee, 0x96, 0x0c, 0x57, 0x10, 0x4a, 0x77, 0xc4, 0x0d, 0x58,
	0xda, 0xed, 0x4d, 0x68, 0x66, 0x40, 0xbc, 0x58, 0x7d, 0xa8, 0x3f, 0xa3, 0x13, 0xc2, 0x38, 0xac,
	0x05, 0xf5, 0xc8, 0x77, 0x92, 0x23, 0x1a, 0x07, 0x2a, 0xb6, 0x4c, 0xe6, 0x36, 0xd7, 0xf7, 0x48,
	0x98, 0x0c, 0x46, 0xaa, 0x2b, 0x32, 0xd9, 0xfe, 0xbd, 0x04, 0xa0, 0x40, 0x78, 0x06, 0x6d, 0xa8,
	0x4e, 0x68, 0xe0, 0x78, 0xa1, 0x04, 0xe9, 0xc3, 0x72, 0xd1, 0x56, 0x1a, 0xac, 0x7e, 0xd1, 0xff,
	0xa1, 0x96, 0xb8, 0xd1, 0x88, 0xc6, 0x89, 0xbc, 0x71, 0xbf, 0xb9, 0x5c, 0xb4, 0xeb, 0x89, 0x1b,
	0xbd, 0x8c, 0x68, 0x9c, 0xe0, 0xd4, 0x88, 0x6e, 0x43, 0xf5, 0x8c, 0x09, 0x37, 0x41, 0x3b, 0xfd,
	0xc6, 0x72, 0xd1, 0xae, 0x9d, 0x31, 0xe9, 0xa5, 0x4c, 0x1c, 0xec, 0x8c, 0x49, 0xaf, 0xca, 0x0a,
	0xec, 0x8c, 0x29, 0xb7, 0xd4, 0x88, 0x3e, 0xb8, 0xf8, 0x0c, 0xf5, 0xfe, 0xc6, 0x72, 0xd1, 0x5e,
	0x29, 0x73, 0xaf, 0x12, 0xb5, 0x41, 0x0f, 0xf9, 0x9d, 0xcc, 0x6a, 0xa7, 0xbc, 0x63, 0xf4, 0x8d,
	0xe5, 0xa2, 0x2d, 0x15, 0x58, 0xfe, 0xa0, 0x07, 0x50, 0x1b, 0x3b, 0xee, 0x09, 0x3d, 0x3a, 0x12,
	0xac, 0xd5, 0xd8, 0xbd, 0x96, 0xef, 0x91, 0xbe, 0x34, 0xc9, 0x80, 0x95, 0x1f, 0x4e, 0x17, 0xe8,
	0x3e, 0x34, 0xb3, 0x93, 0x86, 0xce, 0xb9, 0xa0, 0x38, 0xbd, 0xbf, 0xb5, 0x5c, 0xb4, 0x37, 0x32,
	0xfd, 0xcb, 0xc0, 0x39, 0xc7, 0x05, 0x37, 0xfb, 0x17, 0x0d, 0x6a, 0x0a, 0x18, 0xdd, 0x85, 0xfa,
	0xd0, 0x39, 0x3f, 0x20, 0xbe, 0x23, 0x1b, 0x49, 0xdd, 0x25, 0x70, 0xce, 0x5f, 0x4e, 0xb8, 0x12,
	0x67, 0x66, 0x74, 0x0f, 0x8c, 0xbe, 0xc3, 0x88, 0xf4, 0x95, 0xe9, 0xde, 0x5c, 0x2e, 0xda, 0x30,
	0x76, 0x18, 0x51, 0xce, 0x2b, 0x07, 0x5e, 0xbe, 0x2f, 0x1d, 0x37, 0xa1, 0xf2, 0xa1, 0x97, 0x64,
	0xf9, 0x8e, 0x84, 0x06, 0x2b, 0x0b, 0xf7, 0x79, 0xec, 0x25, 0x09, 0x89, 0x45, 0xc2, 0x95, 0xcf,
	0x2b, 0xa1, 0xc1, 0xca, 0x62, 0x3f, 0x81, 0xc6, 0x63, 0xea, 0x85, 0xbc, 0xf5, 0xd5, 0x1c, 0x98,
	0x31, 0xc1, 0xaa, 0xb2, 0x6d, 0x95, 0x84, 0xee, 0x40, 0x85, 0xc7, 0xa1, 0x1a, 0xb7, 0x55, 0xcc,
	0x21, 0x23, 0x58, 0x58, 0xed, 0x00, 0x36, 0x52, 0x30, 0x82, 0x09, 0x8b, 0xc4, 0x10, 0x26, 0x6c,
	0xe6, 0x27, 0x6a, 0xae, 0x29, 0x89, 0xeb, 0x13, 0x7a, 0xc2, 0xc7, 0xbd, 0x62, 0x01, 0x29, 0x5d,
	0x3a, 0xb4, 0xb7, 0x41, 0xe7, 0x2b, 0x39, 0xb2, 0x0d, 0x2c, 0x05, 0xfb, 0x15, 0x54, 0xf8, 0xe1,
	0x39, 0x34, 0xed, 0x22, 0x9a, 0x1a, 0x6a, 0xa5, 0x8b, 0x1c, 0xa4, 0x48, 0xb5, 0x7c, 0x29, 0xa9,
	0x56, 0x2e, 0x90, 0xea, 0x08, 0x5a, 0x0f, 0x59, 0xe2, 0x8c, 0x7d, 0x8f, 0x1d, 0x73, 0x2e, 0x7a,
	0xf7, 0x64, 0xfd, 0xa6, 0xc1, 0xd6, 0x05, 0x48, 0x16, 0xfd, 0x13, 0xd4, 0x96, 0xab, 0x52, 0xb5,
	0x50, 0xa5, 0x2c, 0xeb, 0xb5, 0x5c, 0xd6, 0x77, 0xff, 0xa8, 0x80, 0xfe, 0x94, 0x5f, 0x06, 0xed,
	0x42, 0x85, 0x93, 0x3f, 0x2a, 0x3c, 0x29, 0xf5, 0x39, 0x60, 0x5d, 0x7f, 0x53, 0xc9, 0xc7, 0xce,
	0x7d, 0xd0, 0xc5, 0x97, 0x04, 0xda, 0xce, 0xdb, 0xd3, 0x8f, 0x0b, 0xeb, 0xc6, 0x1a, 0x2d, 0xdf,
	0xf6, 0x09, 0xd4, 0xd4, 0x17, 0x00, 0x2a, 0xba, 0x64, 0x7c, 0x6c, 0x99, 0x6b, 0xf5, 0x7c, 0xf3,
	0x01, 0xc0, 0x8a, 0x6d, 0x51, 0xe1, 0x13, 0xb5, 0x40, 0xe9, 0xd6, 0xbf, 0x2f, 0x33, 0x71, 0x94,
	0x3d, 0x30, 0x32, 0x0a, 0x45, 0x85, 0xc3, 0xf2, 0x2c, 0x6d, 0x59, 0x97, 0x58, 0x38, 0xc4, 0x67,
	0xd0, 0xc0, 0x24, 0x24, 0x67, 0x92, 0x9a, 0xd0, 0xf5, 0xb5, 0x4c, 0x6a, 0xfd, 0xeb, 0x12, 0x16,
	0xe3, 0x49, 0x50, 0xac, 0x50, 0x4c, 0xc2, 0x8a, 0x73, 0x8a, 0x49, 0xc8, 0x53, 0x08, 0x4f, 0xbc,
	0x98, 0xfe, 0xc5, 0xc4, 0xa7, 0xac, 0x52, 0x4c, 0x7c, 0x8e, 0x26, 0x9e, 0xc2, 0x46, 0xa1, 0x49,
	0xd1, 0xad, 0xbc, 0xe3, 0xc5, 0x27, 0x61, 0xfd, 0xe7, 0x2d, 0x56, 0x16, 0xa1, 0xcf, 0xa1, 0x9e,
	0x0e, 0x08, 0x54, 0xb8, 0x66, 0x6e, 0x06, 0x59, 0x37, 0xd7, 0x19, 0xc4, 0x3c, 0xe9, 0x57, 0xbf,
	0xab, 0xf0, 0x3f, 0x5e, 0xe3, 0xaa, 0xa0, 0xc9, 0x8f, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x68,
	0x7d, 0xee, 0xfa, 0xb1, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// LogicClient is the client API for Logic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogicClient interface {
	// Ping Service
	Ping(ctx context.Context, in *PingReq, opts ...grpc1.CallOption) (*PingReply, error)
	// Close Service
	Close(ctx context.Context, in *CloseReq, opts ...grpc1.CallOption) (*CloseReply, error)
	// Connect
	Connect(ctx context.Context, in *ConnectReq, opts ...grpc1.CallOption) (*ConnectReply, error)
	// Disconnect
	Disconnect(ctx context.Context, in *DisconnectReq, opts ...grpc1.CallOption) (*DisconnectReply, error)
	// Heartbeat
	Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc1.CallOption) (*HeartbeatReply, error)
	// RenewOnlineapi.pb.go
	RenewOnline(ctx context.Context, in *OnlineReq, opts ...grpc1.CallOption) (*OnlineReply, error)
	// Receive
	Receive(ctx context.Context, in *ReceiveReq, opts ...grpc1.CallOption) (*ReceiveReply, error)
	//ServerList
	Nodes(ctx context.Context, in *NodesReq, opts ...grpc1.CallOption) (*NodesReply, error)
	// 建立连接
	EstablishConn(ctx context.Context, in *EstablishConnReq, opts ...grpc1.CallOption) (*EstablishConnResp, error)
	// 进入房间
	JoinRoom(ctx context.Context, in *JoinRoomReq, opts ...grpc1.CallOption) (*JoinRoomeResp, error)
}

type logicClient struct {
	cc *grpc1.ClientConn
}

func NewLogicClient(cc *grpc1.ClientConn) LogicClient {
	return &logicClient{cc}
}

func (c *logicClient) Ping(ctx context.Context, in *PingReq, opts ...grpc1.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) Close(ctx context.Context, in *CloseReq, opts ...grpc1.CallOption) (*CloseReply, error) {
	out := new(CloseReply)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) Connect(ctx context.Context, in *ConnectReq, opts ...grpc1.CallOption) (*ConnectReply, error) {
	out := new(ConnectReply)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) Disconnect(ctx context.Context, in *DisconnectReq, opts ...grpc1.CallOption) (*DisconnectReply, error) {
	out := new(DisconnectReply)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc1.CallOption) (*HeartbeatReply, error) {
	out := new(HeartbeatReply)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) RenewOnline(ctx context.Context, in *OnlineReq, opts ...grpc1.CallOption) (*OnlineReply, error) {
	out := new(OnlineReply)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/RenewOnline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) Receive(ctx context.Context, in *ReceiveReq, opts ...grpc1.CallOption) (*ReceiveReply, error) {
	out := new(ReceiveReply)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/Receive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) Nodes(ctx context.Context, in *NodesReq, opts ...grpc1.CallOption) (*NodesReply, error) {
	out := new(NodesReply)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/Nodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) EstablishConn(ctx context.Context, in *EstablishConnReq, opts ...grpc1.CallOption) (*EstablishConnResp, error) {
	out := new(EstablishConnResp)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/EstablishConn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logicClient) JoinRoom(ctx context.Context, in *JoinRoomReq, opts ...grpc1.CallOption) (*JoinRoomeResp, error) {
	out := new(JoinRoomeResp)
	err := c.cc.Invoke(ctx, "/goim.logic.Logic/JoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicServer is the server API for Logic service.
type LogicServer interface {
	// Ping Service
	Ping(context.Context, *PingReq) (*PingReply, error)
	// Close Service
	Close(context.Context, *CloseReq) (*CloseReply, error)
	// Connect
	Connect(context.Context, *ConnectReq) (*ConnectReply, error)
	// Disconnect
	Disconnect(context.Context, *DisconnectReq) (*DisconnectReply, error)
	// Heartbeat
	Heartbeat(context.Context, *HeartbeatReq) (*HeartbeatReply, error)
	// RenewOnlineapi.pb.go
	RenewOnline(context.Context, *OnlineReq) (*OnlineReply, error)
	// Receive
	Receive(context.Context, *ReceiveReq) (*ReceiveReply, error)
	//ServerList
	Nodes(context.Context, *NodesReq) (*NodesReply, error)
	// 建立连接
	EstablishConn(context.Context, *EstablishConnReq) (*EstablishConnResp, error)
	// 进入房间
	JoinRoom(context.Context, *JoinRoomReq) (*JoinRoomeResp, error)
}

// UnimplementedLogicServer can be embedded to have forward compatible implementations.
type UnimplementedLogicServer struct {
}

func (*UnimplementedLogicServer) Ping(ctx context.Context, req *PingReq) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedLogicServer) Close(ctx context.Context, req *CloseReq) (*CloseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (*UnimplementedLogicServer) Connect(ctx context.Context, req *ConnectReq) (*ConnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedLogicServer) Disconnect(ctx context.Context, req *DisconnectReq) (*DisconnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (*UnimplementedLogicServer) Heartbeat(ctx context.Context, req *HeartbeatReq) (*HeartbeatReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (*UnimplementedLogicServer) RenewOnline(ctx context.Context, req *OnlineReq) (*OnlineReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewOnline not implemented")
}
func (*UnimplementedLogicServer) Receive(ctx context.Context, req *ReceiveReq) (*ReceiveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (*UnimplementedLogicServer) Nodes(ctx context.Context, req *NodesReq) (*NodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Nodes not implemented")
}
func (*UnimplementedLogicServer) EstablishConn(ctx context.Context, req *EstablishConnReq) (*EstablishConnResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstablishConn not implemented")
}
func (*UnimplementedLogicServer) JoinRoom(ctx context.Context, req *JoinRoomReq) (*JoinRoomeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}

func RegisterLogicServer(s *grpc1.Server, srv LogicServer) {
	s.RegisterService(&_Logic_serviceDesc, srv)
}

func _Logic_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).Ping(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).Close(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).Close(ctx, req.(*CloseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).Connect(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).Connect(ctx, req.(*ConnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).Disconnect(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).Disconnect(ctx, req.(*DisconnectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).Heartbeat(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).Heartbeat(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_RenewOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).RenewOnline(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/RenewOnline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).RenewOnline(ctx, req.(*OnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).Receive(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/Receive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).Receive(ctx, req.(*ReceiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_Nodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).Nodes(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/Nodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).Nodes(ctx, req.(*NodesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_EstablishConn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstablishConnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).EstablishConn(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/EstablishConn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).EstablishConn(ctx, req.(*EstablishConnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logic_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicServer).JoinRoom(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goim.logic.Logic/JoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicServer).JoinRoom(ctx, req.(*JoinRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logic_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "goim.logic.Logic",
	HandlerType: (*LogicServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Logic_Ping_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Logic_Close_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _Logic_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Logic_Disconnect_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Logic_Heartbeat_Handler,
		},
		{
			MethodName: "RenewOnline",
			Handler:    _Logic_RenewOnline_Handler,
		},
		{
			MethodName: "Receive",
			Handler:    _Logic_Receive_Handler,
		},
		{
			MethodName: "Nodes",
			Handler:    _Logic_Nodes_Handler,
		},
		{
			MethodName: "EstablishConn",
			Handler:    _Logic_EstablishConn_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _Logic_JoinRoom_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "api.proto",
}
